name: pf_data
version: "1.0.0"
config-version: 2
profile: pf_data
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  pf_data:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
